(deftheme vichangelo-light
  "Created 2023-03-16.")

(custom-theme-set-variables
 'vichangelo-light
 '(display-time-mode t))

(custom-theme-set-faces
 'vichangelo-light
 '(cursor ((t (:background "#505050"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#85DDFF"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#070707"))))
 '(highlight ((t (:background "#070707" :foreground "#fafafa"))))
 '(region ((t (:extend t :background "#282828"))))
 '(shadow ((t (:foreground "#515151"))))
 '(secondary-selection ((t (:extend t :background "#777778"))))
 '(trailing-whitespace ((t (:background "#FF5E5E"))))
 '(font-lock-builtin-face ((t (:foreground "#2a3b55" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#404040" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#775e3b"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#404040" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#aa4949"))))
 '(font-lock-keyword-face ((t (:foreground "#2a3755" :slant italic :weight bold))))
 '(font-lock-negation-char-face ((t (:inherit bold :foreground "#2a3755"))))
 '(font-lock-preprocessor-face ((t (:inherit bold :foreground "#aa4949"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "#aa4949"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "#aa4949"))))
 '(font-lock-string-face ((t (:foreground "#3b552a"))))
 '(font-lock-type-face ((t (:foreground "#422e55"))))
 '(font-lock-variable-name-face ((t (:foreground "#55442a"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:foreground "#070707"))))
 '(fringe ((t (:foreground "#959595" :inherit default))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#d4d4d4" :background "#121212"))))
 '(mode-line ((t (:background "#959595" :foreground "#dfdfdf" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#070707"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#959595" :foreground "#8CDAFF" :box nil))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#171F24" :background "#FF5E5E"))))
 '(lazy-highlight ((t (:weight bold :foreground "#d4d4d4" :background "#4b474c"))))
 '(match ((t (:weight bold :foreground "#468800" :background "#171F24"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground "#aa9966"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#463f4d" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#374b3a" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#53553c" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "#502e2c"))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "#523928"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#463f55" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground "#475255"))))
 '(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground "#555025"))))
 '(rainbow-delimiters-mismatched-face ((default (:inherit (rainbow-delimiters-unmatched-face)))))
 '(rainbow-delimiters-unmatched-face ((default (:inherit (rainbow-delimiters-base-error-face)))))
 '(rainbow-delimiters-base-error-face ((t (:inherit rainbow-delimiters-base-face :foreground "red3"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#fafafa" :foreground "#070707" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal)))))

(provide-theme 'vichangelo-light)
